# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from functools import partial

import requests, sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal, QDate, QDateTime
from PyQt5.QtWidgets import QTableWidgetItem, QMenu, QDateTimeEdit
import log_read
import pyperclip
from log import Log_Ui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 6, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 4, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_4.addWidget(self.tableWidget, 1, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ThinkPHP日志读取"))
        self.label.setText(_translate("MainWindow", "Target:"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "http://www.taget.com/"))
        self.label_4.setText(_translate("MainWindow", "查询范围："))
        self.label_2.setText(_translate("MainWindow", "至"))
        self.label_3.setText(_translate("MainWindow", "自定义路径:"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "输入日期时间路径外完整路径,比如：http://www.taget.com/Application/Runtime/Logs/"))
        self.label_5.setText(_translate("MainWindow", "自定义匹配："))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "自定义查询（需正则）"))
        self.label_6.setText(_translate("MainWindow", "版本："))
        self.comboBox.setItemText(0, _translate("MainWindow", "TP3系列"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TP5系列"))
        self.pushButton.setText(_translate("MainWindow", "开始查找"))
        self.pushButton_2.setText(_translate("MainWindow", "停止"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "url"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "user"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "自定义匹配"))
        self.label_7.setText(_translate("MainWindow", ""))


        self.dateEdit.setDisplayFormat('yyyy-MM-dd')
        self.dateEdit_2.setDisplayFormat('yyyy-MM-dd')
        self.dateEdit.setDate(QDate.currentDate().addDays(-90))
        self.dateEdit_2.setDate(QDate.currentDate())
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit_2.setCalendarPopup(True)
        self.tableWidget.setColumnWidth(0, 600)
        self.tableWidget.setColumnWidth(1, 110)
        self.tableWidget.setColumnWidth(2, 300)
        self.tableWidget.setColumnWidth(3, 500)
        row_cnt = self.tableWidget.rowCount()  # 读取行
        self.tableWidget.insertRow(row_cnt)


        #url = QTableWidgetItem('http://hefq.orangeaiedu.com/Application/Runtime/Logs/Admin/20_11_23.log')
        #user = QTableWidgetItem('admin')
        #passwd = QTableWidgetItem('5f4dcc3b5aa765d61d8327deb882cf99')
        #self.tableWidget.setItem(row_cnt, 0, url)
        #self.tableWidget.setItem(row_cnt, 1, user)
        #self.tableWidget.setItem(row_cnt, 2, passwd)


        self.tableWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget.customContextMenuRequested.connect(self.GenerateMenu)


    def GenerateMenu(self, pos):
        # 计算有多少条数据，默认-1,
        row_num = -1
        for i in self.tableWidget.selectionModel().selection().indexes():
            row_num = i.row()

        # 表格中只有两条有效数据，所以只在前两行支持右键弹出菜单
        menu = QMenu()
        item1 = menu.addAction(u'复制url')
        item2 = menu.addAction(u'复制账号')
        item3 = menu.addAction(u'复制密码')
        item4 = menu.addAction(u'查看完整日志')
        item5 = menu.addAction(u'明文密码')
        action = menu.exec_(self.tableWidget.mapToGlobal(pos))
        # 显示选中行的数据文本
        if action == item1:
            try:
                pyperclip.copy(self.tableWidget.item(row_num, 0).text())
            except:
                pass

        if action == item2:
            try:
                pyperclip.copy(self.tableWidget.item(row_num, 1).text())
            except:
                pass

        if action == item3:
            try:
                pyperclip.copy(self.tableWidget.item(row_num, 2).text())
            except:
                pass

        if action == item4:
            lg.show()
            try:
                curr_log = requests.get(url=self.tableWidget.item(row_num, 0).text(),verify=False)
                log.textBrowser.setText(curr_log.text)
            except:
                pass

        if action == item5:
            try:
                #print(type(self.tableWidget.item(row_num, 2).text()))
                #passwd = log_read.md5_decrypt(self.tableWidget.item(row_num, 2).text())
                show_message(ui,'抱歉，暂无接口')
            except:
                pass


def show_message(ui,msg):
    QtWidgets.QMessageBox.information(ui.pushButton, "提示", msg)



def key_function(ui):
    #ui.pushButton.clicked.connect(partial(log_read.main_task,ui))


    class Queryhost_MyThread(QThread):
        my_signal = pyqtSignal(object, str)
        def __init__(self):
            super().__init__()

        def run(self):
            massage = log_read.main_task(ui)
            if massage is not None:
                self.my_signal.emit(massage[0], massage[1])

    Queryhost_thread = Queryhost_MyThread()
    Queryhost_thread.my_signal.connect(show_message)
    ui.pushButton.clicked.connect(partial(Queryhost_thread.start))


if  __name__=="__main__":
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QMainWindow()
    lg = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    log = Log_Ui()
    ui.setupUi(widget)
    log.setupUi(lg)
    widget.show()
    key_function(ui)
    sys.exit(app.exec_())
